#!/bin/bash

echo "=========================================="
echo "🔧 הוספת Environment Variables ל-Vercel"
echo "=========================================="
echo ""
echo "פתח את הדף הזה עכשיו:"
echo "👉 https://vercel.com/yossi121212/newvsold/settings/environment-variables"
echo ""
echo "=========================================="
echo "📝 משתנה 1 - URL"
echo "=========================================="
echo ""
echo "לחץ 'Add New' והכנס:"
echo ""
echo "Key (שדה שמאלי):"
echo "NEXT_PUBLIC_SUPABASE_URL"
echo ""
echo "Value (שדה ימני):"
echo "https://ewfrofdnvqdcvfffzpdw.supabase.co"
echo ""
echo "Environments: סמן את כל 3 - Production, Preview, Development"
echo ""
echo "לחץ Save"
echo ""
echo "=========================================="
echo "📝 משתנה 2 - API KEY"
echo "=========================================="
echo ""
echo "לחץ שוב 'Add New' והכנס:"
echo ""
echo "Key (שדה שמאלי):"
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo ""
echo "Value (שדה ימני - העתק את כל השורה):"
echo "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3ZnJvZmRudnFkY3ZmZmZ6cGR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwOTM4NDcsImV4cCI6MjA3OTY2OTg0N30.WkdY8QMdba5GNhJvoTXPNmA1uMY2QR3Uw3obqfN3ldw"
echo ""
echo "Environments: סמן את כל 3"
echo ""
echo "לחץ Save"
echo ""
echo "=========================================="
echo "🚀 REDEPLOY"
echo "=========================================="
echo ""
echo "אחרי ששמרת את 2 המשתנים:"
echo ""
echo "1. לך ל: https://vercel.com/yossi121212/newvsold"
echo "2. לחץ על Deployments"
echo "3. על הראשון ברשימה - לחץ ⋯ (3 נקודות)"
echo "4. בחר Redeploy"
echo "5. לחץ Redeploy באישור"
echo ""
echo "⏱️ אחרי 1-2 דקות - זה יעבוד עם Supabase!"
echo ""
